name: Lint, Build & Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ['docs/**']

jobs:
  all:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node-version: ['14', '16.10']
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} | Node ${{ matrix.node-version }} latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.4

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Docs
        id: docs
        uses: ./.github/actions/docs
        with:
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}

      - run: 'echo "No lint, build, & test required"'
