name: Publish release candidate

on:
  push:
    branches: ['release/**']
    tags-ignore:
      - v** # We don't want this to run on release

jobs:
  build:
    if: github.repository == 'redwoodjs/redwood'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required because lerna uses tags to determine the version.

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Save branch latest tag and name to env var
        run: |
          echo 'BRANCH_TAG='$(git describe)>>$GITHUB_ENV
          echo 'BRANCH_NAME'=${{github.ref_name}}>>$GITHUB_ENV
          echo $BRANCH_TAG
          echo $BRANCH_NAME


      - name: Save branch name to env var
        run: |
          echo "git describe
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc


      - name: Install dependencies
        run: yarn install --immutable --check-files

      - name: Build
        run: yarn build

      - name: Run ESLint
        run: yarn lint
        env:
          CI: true

      - name: Run tests
        run: yarn test
        env:
          CI: true

      - name: Should I publish
        run: |
          ./tasks/public-rc

      - name: Publish
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
          yarn publish:rc-${version}
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Cleanup
        run |
          # reset env vars
          # or at beginning of run we check if Env Vars exist
